name:                DerivativeCalc
version:             0.4.3
github:              "youcefs21/DerivativeCalc"
license:             AGPL-3
author:              "Youcef Boumar"
maintainer:          "youcefs2121@gmail.com"
copyright:           "2021 Youcef Boumar"

extra-source-files:
- README.md
- ChangeLog.md


description:         Please see the README on GitHub at <https://github.com/youcefs21/DerivativeCalc#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  DerivativeCalc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DerivativeCalc

tests:
  DerivativeCalc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DerivativeCalc
